const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const WebSocket=require('ws');
const PORT=process.env.PORT||10000, ROOT=__dirname, rooms=new Map();
const COLORS=['red','yellow','green','blue'], SPECIAL=['skip','reverse','draw2'];
function send(p,x){if(p?.ws?.readyState===WebSocket.OPEN)p.ws.send(JSON.stringify(x))}
function broadcast(r,x){r.players.forEach(p=>send(p,x))}
function code(){let c;do c=Math.random().toString(36).slice(2,6).toUpperCase();while(rooms.has(c));return c}
function shuffle(a){for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}}
function deck(){let d=[],id=1,add=(c,v)=>d.push({id:id++,color:c,value:v});for(const c of COLORS){add(c,'0');for(let n=1;n<10;n++){add(c,''+n);add(c,''+n)}for(const s of SPECIAL){add(c,s);add(c,s)}}for(let i=0;i<4;i++){add('wild','wild');add('wild','draw4')}return d}
function draw(r,p,n=1){for(let i=0;i<n;i++){if(!r.deck.length&&r.used.length){r.deck=r.used.splice(0);shuffle(r.deck)}if(r.deck.length)p.hand.push(r.deck.pop())}}
function next(r){r.turn=(r.turn+r.dir+r.players.length)%r.players.length}
function lobby(r){return{type:'room',room:r.code,game:r.game,host:r.players[0]?.id,players:r.players.map(p=>({id:p.id,name:p.name}))}}
function unoState(r,p){return{game:'uno',room:r.code,me:p.id,turn:r.turn,color:r.color,awaitColor:r.awaitColor,discard:r.discard,players:r.players.map(x=>({id:x.id,name:x.name,hand:x.hand}))}}
function valid(c,r){return !r.discard||c.color==='wild'||c.color===r.color||c.color===r.discard.color||c.value===r.discard.value}
function effects(r,c){if(c.value==='reverse')r.dir*=-1;if(c.value==='skip')next(r);if(c.value==='draw2'){draw(r,r.players[(r.turn+r.dir+r.players.length)%r.players.length],2);next(r)}if(c.value==='draw4'){draw(r,r.players[(r.turn+r.dir+r.players.length)%r.players.length],4);next(r)}}
function startUno(r){r.deck=deck();shuffle(r.deck);r.used=[];r.turn=0;r.dir=1;r.color=null;r.awaitColor=false;r.players.forEach(p=>p.hand=[]);for(let i=0;i<7;i++)r.players.forEach(p=>draw(r,p));do r.discard=r.deck.pop();while(r.discard.color==='wild');r.color=r.discard.color;r.started=true;r.players.forEach(p=>send(p,{type:'started',state:unoState(r,p)}))}
function updateUno(r){r.players.forEach(p=>send(p,{type:'state',state:unoState(r,p)}))}
function playUno(r,p,cid){if(!r.started||r.players[r.turn]!==p||r.awaitColor)return;let i=p.hand.findIndex(c=>String(c.id)===String(cid));if(i<0)return;let c=p.hand[i];if(!valid(c,r))return send(p,{type:'error',message:'هذه الورقة غير صالحة الآن'});p.hand.splice(i,1);if(r.discard)r.used.push(r.discard);r.discard=c;if(c.color==='wild'){r.color=null;r.awaitColor=true}else r.color=c.color;if(!p.hand.length){r.started=false;broadcast(r,{type:'win',message:'🏆 '+p.name+' فاز في UNO!'});return updateUno(r)}if(!r.awaitColor){effects(r,c);next(r)}updateUno(r)}
function xoWinner(b){for(const q of [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]]){let[a,c,d]=q;if(b[a]&&b[a]===b[c]&&b[a]===b[d])return b[a]}return b.every(Boolean)?'draw':null}
function xoState(r){return{game:'xo',room:r.code,turn:r.turn,board:r.board,winner:r.winner,players:r.players.map(p=>({id:p.id,name:p.name,symbol:p.symbol}))}}
function startXO(r){r.board=Array(9).fill(null);r.turn=0;r.winner=null;r.started=true;r.players.forEach((p,i)=>p.symbol=i?'O':'X');broadcast(r,{type:'started',state:xoState(r)})}
function playXO(r,p,pos){if(!r.started||r.players[r.turn]!==p||r.board[pos]!=null)return;r.board[pos]=p.symbol;r.winner=xoWinner(r.board);if(!r.winner)r.turn=(r.turn+1)%r.players.length;else r.started=false;broadcast(r,{type:'state',state:xoState(r)})}
function bowlState(r){return{game:'bowling',room:r.code,turn:r.turn,frame:r.frame,roll:r.roll,pins:r.pins,scores:r.players.map(p=>({id:p.id,name:p.name,score:p.score}))}}
function startBowl(r){r.turn=0;r.frame=1;r.roll=0;r.pins=10;r.started=true;r.players.forEach(p=>p.score=0);broadcast(r,{type:'started',state:bowlState(r)})}
function bowl(r,p,power){if(!r.started||r.players[r.turn]!==p)return;let k=Math.min(r.pins,Math.max(0,Math.round((Math.random()*.35+.65*Math.max(0,Math.min(1,Number(power)||.7)))*r.pins)));r.pins-=k;p.score+=k;if(r.roll===0&&r.pins>0)r.roll=1;else{r.roll=0;r.pins=10;r.turn=(r.turn+1)%r.players.length;if(r.turn===0)r.frame++;}if(r.frame>10){r.started=false;broadcast(r,{type:'win',message:'🎳 انتهت مباراة البولنق!'})}broadcast(r,{type:'state',state:bowlState(r)})}
function poolState(r){return{game:'billiards',room:r.code,turn:r.turn,balls:r.balls,score:r.players.map(p=>({id:p.id,name:p.name,score:p.score}))}}
function startPool(r){r.turn=0;r.started=true;r.balls=Array.from({length:10},(_,i)=>({id:i+1,on:true}));r.players.forEach(p=>p.score=0);broadcast(r,{type:'started',state:poolState(r)})}
function shoot(r,p,aim){if(!r.started||r.players[r.turn]!==p)return;let live=r.balls.filter(b=>b.on);if(live.length&&Math.random()<.25+.65*(1-Math.abs(50-(Number(aim)||50))/50)){live[Math.floor(Math.random()*live.length)].on=false;p.score++}if(r.balls.some(b=>b.on))r.turn=(r.turn+1)%r.players.length;else{r.started=false;broadcast(r,{type:'win',message:'🎱 انتهت مباراة البلياردو!'})}broadcast(r,{type:'state',state:poolState(r)})}
const server=http.createServer((req,res)=>{let u=(req.url||'/').split('?')[0];if(u==='/')u='/index.html';let f=path.join(ROOT,path.normalize(u).replace(/^\.{2}(\/|\\)/,''));if(!f.startsWith(ROOT)||!fs.existsSync(f)||!fs.statSync(f).isFile()){res.writeHead(404);return res.end('Not Found')}let m={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8'};res.writeHead(200,{'Content-Type':m[path.extname(f)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(fs.readFileSync(f))});
const wss=new WebSocket.Server({server});
wss.on('connection',ws=>{let p=null,r=null;send({ws},{type:'connected'});ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}
if(m.type==='create'){if(p)return;r={code:code(),game:['uno','xo','bowling','billiards'].includes(m.game)?m.game:'uno',players:[],started:false,deck:[],used:[],discard:null,turn:0,dir:1,color:null,awaitColor:false,board:[],winner:null,frame:1,roll:0,pins:10,balls:[]};p={id:crypto.randomUUID(),name:String(m.name||'لاعب').trim().slice(0,18)||'لاعب',hand:[],ws};r.players.push(p);rooms.set(r.code,r);send(p,lobby(r));return}
if(m.type==='join'){r=rooms.get(String(m.room||'').trim().toUpperCase());if(!r)return send({ws},{type:'error',message:'الغرفة غير موجودة'});if(r.started)return send({ws},{type:'error',message:'اللعبة بدأت بالفعل'});if(r.players.length>=4)return send({ws},{type:'error',message:'الغرفة ممتلئة'});if(m.game&&m.game!==r.game)return send({ws},{type:'error',message:'هذه الغرفة للعبة '+r.game});p={id:crypto.randomUUID(),name:String(m.name||'لاعب').trim().slice(0,18)||'لاعب',hand:[],ws};r.players.push(p);broadcast(r,lobby(r));return}
if(!p||!r)return send({ws},{type:'error',message:'أنشئ غرفة أو انضم أولاً'});
if(m.type==='start'){if(r.players[0]!==p)return send(p,{type:'error',message:'فقط المضيف يستطيع البدء'});if(r.game==='uno')startUno(r);else if(r.game==='xo')startXO(r);else if(r.game==='bowling')startBowl(r);else startPool(r);return}
if(m.type==='play'&&r.game==='uno')return playUno(r,p,m.id);if(m.type==='draw'&&r.game==='uno'){if(r.started&&r.players[r.turn]===p&&!r.awaitColor){draw(r,p);next(r);updateUno(r)}return}if(m.type==='color'&&r.game==='uno'){if(r.started&&r.players[r.turn]===p&&r.awaitColor&&COLORS.includes(m.color)){r.color=m.color;r.awaitColor=false;effects(r,r.discard);next(r);updateUno(r)}return}if(m.type==='uno'){if(r.game==='uno'&&p.hand.length===1)broadcast(r,{type:'toast',message:'🔥 '+p.name+' قال UNO!'});return}if(m.type==='xo'&&r.game==='xo')return playXO(r,p,Number(m.pos));if(m.type==='bowl'&&r.game==='bowling')return bowl(r,p,m.power);if(m.type==='billiards'&&r.game==='billiards')return shoot(r,p,m.aim);if(m.type==='chat'){let t=String(m.text||'').trim().slice(0,180);if(t)broadcast(r,{type:'chat',name:p.name,text:t})}
});ws.on('close',()=>{if(!p||!r)return;r.players=r.players.filter(x=>x!==p);if(!r.players.length){rooms.delete(r.code);return}if(r.started){r.started=false;broadcast(r,{type:'error',message:'⚠️ خرج أحد اللاعبين وتم إيقاف المباراة.'})}broadcast(r,lobby(r))})});
server.listen(PORT,'0.0.0.0',()=>console.log('UNO Arcade running on port '+PORT));
